/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AnimationEffect = { 'particle' : null } |
  { 'scale' : null } |
  { 'rotate' : null };
export interface AnimationProfile2D {
  'keyframes' : Array<Keyframe2D>,
  'effects' : Array<AnimationEffect>,
  'effectConfig2D' : EffectConfig2D,
  'rotationConfig' : RotationConfig2D,
}
export interface AnimationProfile3D {
  'keyframes' : Array<Keyframe3D>,
  'effects' : Array<AnimationEffect>,
  'effectConfig3D' : EffectConfig3D,
  'rotationConfig' : RotationConfig3D,
}
export interface EffectConfig2D { 'rotateIntensity' : number }
export interface EffectConfig3D { 'particleIntensity' : number }
export type ExternalBlob = Uint8Array;
export interface Keyframe2D {
  'rotation' : Rotation2D,
  'time' : number,
  'scale' : Scale2D,
  'position' : Position2D,
  'intensity' : number,
}
export interface Keyframe3D {
  'rotation' : Rotation3D,
  'time' : number,
  'scale' : Scale3D,
  'position' : Position3D,
  'intensity' : number,
}
export interface LogoData {
  'id' : string,
  'animationProfile2D' : AnimationProfile2D,
  'animationProfile3D' : AnimationProfile3D,
  'inputImage' : ExternalBlob,
  'videoFile' : [] | [ExternalBlob],
  'modelFile' : [] | [ExternalBlob],
  'workflowMode' : WorkflowMode,
}
export type Position2D = [number, number];
export type Position3D = [number, number, number];
export interface ResponsePayload {
  'rotation' : Array<LogoData>,
  'noEffect' : Array<LogoData>,
  'noParticle' : Array<LogoData>,
  'effect' : Array<LogoData>,
  'particle' : Array<LogoData>,
  'scale' : Array<LogoData>,
}
export type Rotation2D = [number, number];
export type Rotation3D = [number, number, number];
export interface RotationConfig2D {
  'angle' : number,
  'axis' : string,
  'amplitude' : number,
  'speed' : number,
  'frequency' : number,
}
export interface RotationConfig3D {
  'angle' : number,
  'axis' : string,
  'amplitude' : number,
  'speed' : number,
  'frequency' : number,
}
export type Scale2D = [number, number];
export type Scale3D = [number, number, number];
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type WorkflowMode = { 'threeDimensional' : null } |
  { 'twoDimensional' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addAnimationProfile' : ActorMethod<
    [
      string,
      Array<AnimationEffect>,
      EffectConfig2D,
      RotationConfig2D,
      Array<Keyframe2D>,
      Array<AnimationEffect>,
      EffectConfig3D,
      RotationConfig3D,
      Array<Keyframe3D>,
    ],
    string
  >,
  'addLogo' : ActorMethod<
    [
      string,
      WorkflowMode,
      ExternalBlob,
      [] | [ExternalBlob],
      [] | [ExternalBlob],
    ],
    undefined
  >,
  'analyzeAnimation' : ActorMethod<[ExternalBlob, string], string>,
  'analyzeFile' : ActorMethod<[string, ExternalBlob], string>,
  'autoAddAnimationProfile' : ActorMethod<[string], string>,
  'filterAnimationProfiles' : ActorMethod<[string], ResponsePayload>,
  'getAllAnimationProfiles2D' : ActorMethod<[], Array<AnimationProfile2D>>,
  'getAllAnimationProfiles3D' : ActorMethod<[], Array<AnimationProfile3D>>,
  'getAllLogos' : ActorMethod<[], [] | [ResponsePayload]>,
  'getExternalBlobTest' : ActorMethod<[], string>,
  'getLogoById' : ActorMethod<[string], LogoData>,
  'getLogoByIndex' : ActorMethod<[bigint], LogoData>,
  'getWorkflowModeById' : ActorMethod<[string], WorkflowMode>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];