/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const AnimationEffect = IDL.Variant({
  'particle' : IDL.Null,
  'scale' : IDL.Null,
  'rotate' : IDL.Null,
});
export const EffectConfig2D = IDL.Record({ 'rotateIntensity' : IDL.Float64 });
export const RotationConfig2D = IDL.Record({
  'angle' : IDL.Float64,
  'axis' : IDL.Text,
  'amplitude' : IDL.Float64,
  'speed' : IDL.Float64,
  'frequency' : IDL.Float64,
});
export const Rotation2D = IDL.Tuple(IDL.Float64, IDL.Float64);
export const Scale2D = IDL.Tuple(IDL.Float64, IDL.Float64);
export const Position2D = IDL.Tuple(IDL.Float64, IDL.Float64);
export const Keyframe2D = IDL.Record({
  'rotation' : Rotation2D,
  'time' : IDL.Float64,
  'scale' : Scale2D,
  'position' : Position2D,
  'intensity' : IDL.Float64,
});
export const EffectConfig3D = IDL.Record({ 'particleIntensity' : IDL.Float64 });
export const RotationConfig3D = IDL.Record({
  'angle' : IDL.Float64,
  'axis' : IDL.Text,
  'amplitude' : IDL.Float64,
  'speed' : IDL.Float64,
  'frequency' : IDL.Float64,
});
export const Rotation3D = IDL.Tuple(IDL.Float64, IDL.Float64, IDL.Float64);
export const Scale3D = IDL.Tuple(IDL.Float64, IDL.Float64, IDL.Float64);
export const Position3D = IDL.Tuple(IDL.Float64, IDL.Float64, IDL.Float64);
export const Keyframe3D = IDL.Record({
  'rotation' : Rotation3D,
  'time' : IDL.Float64,
  'scale' : Scale3D,
  'position' : Position3D,
  'intensity' : IDL.Float64,
});
export const WorkflowMode = IDL.Variant({
  'threeDimensional' : IDL.Null,
  'twoDimensional' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const AnimationProfile2D = IDL.Record({
  'keyframes' : IDL.Vec(Keyframe2D),
  'effects' : IDL.Vec(AnimationEffect),
  'effectConfig2D' : EffectConfig2D,
  'rotationConfig' : RotationConfig2D,
});
export const AnimationProfile3D = IDL.Record({
  'keyframes' : IDL.Vec(Keyframe3D),
  'effects' : IDL.Vec(AnimationEffect),
  'effectConfig3D' : EffectConfig3D,
  'rotationConfig' : RotationConfig3D,
});
export const LogoData = IDL.Record({
  'id' : IDL.Text,
  'animationProfile2D' : AnimationProfile2D,
  'animationProfile3D' : AnimationProfile3D,
  'inputImage' : ExternalBlob,
  'videoFile' : IDL.Opt(ExternalBlob),
  'modelFile' : IDL.Opt(ExternalBlob),
  'workflowMode' : WorkflowMode,
});
export const ResponsePayload = IDL.Record({
  'rotation' : IDL.Vec(LogoData),
  'noEffect' : IDL.Vec(LogoData),
  'noParticle' : IDL.Vec(LogoData),
  'effect' : IDL.Vec(LogoData),
  'particle' : IDL.Vec(LogoData),
  'scale' : IDL.Vec(LogoData),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addAnimationProfile' : IDL.Func(
      [
        IDL.Text,
        IDL.Vec(AnimationEffect),
        EffectConfig2D,
        RotationConfig2D,
        IDL.Vec(Keyframe2D),
        IDL.Vec(AnimationEffect),
        EffectConfig3D,
        RotationConfig3D,
        IDL.Vec(Keyframe3D),
      ],
      [IDL.Text],
      [],
    ),
  'addLogo' : IDL.Func(
      [
        IDL.Text,
        WorkflowMode,
        ExternalBlob,
        IDL.Opt(ExternalBlob),
        IDL.Opt(ExternalBlob),
      ],
      [],
      [],
    ),
  'analyzeAnimation' : IDL.Func([ExternalBlob, IDL.Text], [IDL.Text], []),
  'analyzeFile' : IDL.Func([IDL.Text, ExternalBlob], [IDL.Text], []),
  'autoAddAnimationProfile' : IDL.Func([IDL.Text], [IDL.Text], []),
  'filterAnimationProfiles' : IDL.Func(
      [IDL.Text],
      [ResponsePayload],
      ['query'],
    ),
  'getAllAnimationProfiles2D' : IDL.Func(
      [],
      [IDL.Vec(AnimationProfile2D)],
      ['query'],
    ),
  'getAllAnimationProfiles3D' : IDL.Func(
      [],
      [IDL.Vec(AnimationProfile3D)],
      ['query'],
    ),
  'getAllLogos' : IDL.Func([], [IDL.Opt(ResponsePayload)], ['query']),
  'getExternalBlobTest' : IDL.Func([], [IDL.Text], []),
  'getLogoById' : IDL.Func([IDL.Text], [LogoData], ['query']),
  'getLogoByIndex' : IDL.Func([IDL.Nat], [LogoData], ['query']),
  'getWorkflowModeById' : IDL.Func([IDL.Text], [WorkflowMode], ['query']),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const AnimationEffect = IDL.Variant({
    'particle' : IDL.Null,
    'scale' : IDL.Null,
    'rotate' : IDL.Null,
  });
  const EffectConfig2D = IDL.Record({ 'rotateIntensity' : IDL.Float64 });
  const RotationConfig2D = IDL.Record({
    'angle' : IDL.Float64,
    'axis' : IDL.Text,
    'amplitude' : IDL.Float64,
    'speed' : IDL.Float64,
    'frequency' : IDL.Float64,
  });
  const Rotation2D = IDL.Tuple(IDL.Float64, IDL.Float64);
  const Scale2D = IDL.Tuple(IDL.Float64, IDL.Float64);
  const Position2D = IDL.Tuple(IDL.Float64, IDL.Float64);
  const Keyframe2D = IDL.Record({
    'rotation' : Rotation2D,
    'time' : IDL.Float64,
    'scale' : Scale2D,
    'position' : Position2D,
    'intensity' : IDL.Float64,
  });
  const EffectConfig3D = IDL.Record({ 'particleIntensity' : IDL.Float64 });
  const RotationConfig3D = IDL.Record({
    'angle' : IDL.Float64,
    'axis' : IDL.Text,
    'amplitude' : IDL.Float64,
    'speed' : IDL.Float64,
    'frequency' : IDL.Float64,
  });
  const Rotation3D = IDL.Tuple(IDL.Float64, IDL.Float64, IDL.Float64);
  const Scale3D = IDL.Tuple(IDL.Float64, IDL.Float64, IDL.Float64);
  const Position3D = IDL.Tuple(IDL.Float64, IDL.Float64, IDL.Float64);
  const Keyframe3D = IDL.Record({
    'rotation' : Rotation3D,
    'time' : IDL.Float64,
    'scale' : Scale3D,
    'position' : Position3D,
    'intensity' : IDL.Float64,
  });
  const WorkflowMode = IDL.Variant({
    'threeDimensional' : IDL.Null,
    'twoDimensional' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const AnimationProfile2D = IDL.Record({
    'keyframes' : IDL.Vec(Keyframe2D),
    'effects' : IDL.Vec(AnimationEffect),
    'effectConfig2D' : EffectConfig2D,
    'rotationConfig' : RotationConfig2D,
  });
  const AnimationProfile3D = IDL.Record({
    'keyframes' : IDL.Vec(Keyframe3D),
    'effects' : IDL.Vec(AnimationEffect),
    'effectConfig3D' : EffectConfig3D,
    'rotationConfig' : RotationConfig3D,
  });
  const LogoData = IDL.Record({
    'id' : IDL.Text,
    'animationProfile2D' : AnimationProfile2D,
    'animationProfile3D' : AnimationProfile3D,
    'inputImage' : ExternalBlob,
    'videoFile' : IDL.Opt(ExternalBlob),
    'modelFile' : IDL.Opt(ExternalBlob),
    'workflowMode' : WorkflowMode,
  });
  const ResponsePayload = IDL.Record({
    'rotation' : IDL.Vec(LogoData),
    'noEffect' : IDL.Vec(LogoData),
    'noParticle' : IDL.Vec(LogoData),
    'effect' : IDL.Vec(LogoData),
    'particle' : IDL.Vec(LogoData),
    'scale' : IDL.Vec(LogoData),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addAnimationProfile' : IDL.Func(
        [
          IDL.Text,
          IDL.Vec(AnimationEffect),
          EffectConfig2D,
          RotationConfig2D,
          IDL.Vec(Keyframe2D),
          IDL.Vec(AnimationEffect),
          EffectConfig3D,
          RotationConfig3D,
          IDL.Vec(Keyframe3D),
        ],
        [IDL.Text],
        [],
      ),
    'addLogo' : IDL.Func(
        [
          IDL.Text,
          WorkflowMode,
          ExternalBlob,
          IDL.Opt(ExternalBlob),
          IDL.Opt(ExternalBlob),
        ],
        [],
        [],
      ),
    'analyzeAnimation' : IDL.Func([ExternalBlob, IDL.Text], [IDL.Text], []),
    'analyzeFile' : IDL.Func([IDL.Text, ExternalBlob], [IDL.Text], []),
    'autoAddAnimationProfile' : IDL.Func([IDL.Text], [IDL.Text], []),
    'filterAnimationProfiles' : IDL.Func(
        [IDL.Text],
        [ResponsePayload],
        ['query'],
      ),
    'getAllAnimationProfiles2D' : IDL.Func(
        [],
        [IDL.Vec(AnimationProfile2D)],
        ['query'],
      ),
    'getAllAnimationProfiles3D' : IDL.Func(
        [],
        [IDL.Vec(AnimationProfile3D)],
        ['query'],
      ),
    'getAllLogos' : IDL.Func([], [IDL.Opt(ResponsePayload)], ['query']),
    'getExternalBlobTest' : IDL.Func([], [IDL.Text], []),
    'getLogoById' : IDL.Func([IDL.Text], [LogoData], ['query']),
    'getLogoByIndex' : IDL.Func([IDL.Nat], [LogoData], ['query']),
    'getWorkflowModeById' : IDL.Func([IDL.Text], [WorkflowMode], ['query']),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };