/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Rotation2D = [number, number];
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface Keyframe2D {
    rotation: Rotation2D;
    time: number;
    scale: Scale2D;
    position: Position2D;
    intensity: number;
}
export type Position2D = [number, number];
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface AnimationProfile2D {
    keyframes: Array<Keyframe2D>;
    effects: Array<AnimationEffect>;
    effectConfig2D: EffectConfig2D;
    rotationConfig: RotationConfig2D;
}
export interface ResponsePayload {
    rotation: Array<LogoData>;
    noEffect: Array<LogoData>;
    noParticle: Array<LogoData>;
    effect: Array<LogoData>;
    particle: Array<LogoData>;
    scale: Array<LogoData>;
}
export interface Keyframe3D {
    rotation: Rotation3D;
    time: number;
    scale: Scale3D;
    position: Position3D;
    intensity: number;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type Position3D = [number, number, number];
export interface http_header {
    value: string;
    name: string;
}
export type Rotation3D = [number, number, number];
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface AnimationProfile3D {
    keyframes: Array<Keyframe3D>;
    effects: Array<AnimationEffect>;
    effectConfig3D: EffectConfig3D;
    rotationConfig: RotationConfig3D;
}
export interface LogoData {
    id: string;
    animationProfile2D: AnimationProfile2D;
    animationProfile3D: AnimationProfile3D;
    inputImage: ExternalBlob;
    videoFile?: ExternalBlob;
    modelFile?: ExternalBlob;
    workflowMode: WorkflowMode;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface RotationConfig3D {
    angle: number;
    axis: string;
    amplitude: number;
    speed: number;
    frequency: number;
}
export interface EffectConfig3D {
    particleIntensity: number;
}
export interface RotationConfig2D {
    angle: number;
    axis: string;
    amplitude: number;
    speed: number;
    frequency: number;
}
export interface EffectConfig2D {
    rotateIntensity: number;
}
export type Scale3D = [number, number, number];
export type Scale2D = [number, number];
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum AnimationEffect {
    particle = "particle",
    scale = "scale",
    rotate = "rotate"
}
export enum WorkflowMode {
    threeDimensional = "threeDimensional",
    twoDimensional = "twoDimensional"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addAnimationProfile(logoId: string, effects2D: Array<AnimationEffect>, effectConfig2D: EffectConfig2D, rotationConfig2D: RotationConfig2D, keyframes2D: Array<Keyframe2D>, effects3D: Array<AnimationEffect>, effectConfig3D: EffectConfig3D, rotationConfig3D: RotationConfig3D, keyframes3D: Array<Keyframe3D>): Promise<string>;
    addLogo(logoId: string, workflowMode: WorkflowMode, inputImage: ExternalBlob, modelFile: ExternalBlob | null, videoFile: ExternalBlob | null): Promise<void>;
    analyzeAnimation(_filepath: ExternalBlob, _animation_type: string): Promise<string>;
    analyzeFile(fileType: string, _blob: ExternalBlob): Promise<string>;
    autoAddAnimationProfile(logoId: string): Promise<string>;
    filterAnimationProfiles(filterType: string): Promise<ResponsePayload>;
    getAllAnimationProfiles2D(): Promise<Array<AnimationProfile2D>>;
    getAllAnimationProfiles3D(): Promise<Array<AnimationProfile3D>>;
    getAllLogos(): Promise<ResponsePayload | null>;
    getExternalBlobTest(): Promise<string>;
    getLogoById(logoId: string): Promise<LogoData>;
    getLogoByIndex(index: bigint): Promise<LogoData>;
    getWorkflowModeById(logoId: string): Promise<WorkflowMode>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
}
import type { AnimationEffect as _AnimationEffect, AnimationProfile2D as _AnimationProfile2D, AnimationProfile3D as _AnimationProfile3D, EffectConfig2D as _EffectConfig2D, EffectConfig3D as _EffectConfig3D, ExternalBlob as _ExternalBlob, Keyframe2D as _Keyframe2D, Keyframe3D as _Keyframe3D, LogoData as _LogoData, ResponsePayload as _ResponsePayload, RotationConfig2D as _RotationConfig2D, RotationConfig3D as _RotationConfig3D, WorkflowMode as _WorkflowMode, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addAnimationProfile(arg0: string, arg1: Array<AnimationEffect>, arg2: EffectConfig2D, arg3: RotationConfig2D, arg4: Array<Keyframe2D>, arg5: Array<AnimationEffect>, arg6: EffectConfig3D, arg7: RotationConfig3D, arg8: Array<Keyframe3D>): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addAnimationProfile(arg0, to_candid_vec_n8(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, to_candid_vec_n8(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAnimationProfile(arg0, to_candid_vec_n8(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, to_candid_vec_n8(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8);
            return result;
        }
    }
    async addLogo(arg0: string, arg1: WorkflowMode, arg2: ExternalBlob, arg3: ExternalBlob | null, arg4: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addLogo(arg0, to_candid_WorkflowMode_n11(this._uploadFile, this._downloadFile, arg1), await to_candid_ExternalBlob_n13(this._uploadFile, this._downloadFile, arg2), await to_candid_opt_n14(this._uploadFile, this._downloadFile, arg3), await to_candid_opt_n14(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLogo(arg0, to_candid_WorkflowMode_n11(this._uploadFile, this._downloadFile, arg1), await to_candid_ExternalBlob_n13(this._uploadFile, this._downloadFile, arg2), await to_candid_opt_n14(this._uploadFile, this._downloadFile, arg3), await to_candid_opt_n14(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async analyzeAnimation(arg0: ExternalBlob, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.analyzeAnimation(await to_candid_ExternalBlob_n13(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.analyzeAnimation(await to_candid_ExternalBlob_n13(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async analyzeFile(arg0: string, arg1: ExternalBlob): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.analyzeFile(arg0, await to_candid_ExternalBlob_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.analyzeFile(arg0, await to_candid_ExternalBlob_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async autoAddAnimationProfile(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.autoAddAnimationProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.autoAddAnimationProfile(arg0);
            return result;
        }
    }
    async filterAnimationProfiles(arg0: string): Promise<ResponsePayload> {
        if (this.processError) {
            try {
                const result = await this.actor.filterAnimationProfiles(arg0);
                return from_candid_ResponsePayload_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterAnimationProfiles(arg0);
            return from_candid_ResponsePayload_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAnimationProfiles2D(): Promise<Array<AnimationProfile2D>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAnimationProfiles2D();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAnimationProfiles2D();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAnimationProfiles3D(): Promise<Array<AnimationProfile3D>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAnimationProfiles3D();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAnimationProfiles3D();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllLogos(): Promise<ResponsePayload | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLogos();
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLogos();
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExternalBlobTest(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getExternalBlobTest();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExternalBlobTest();
            return result;
        }
    }
    async getLogoById(arg0: string): Promise<LogoData> {
        if (this.processError) {
            try {
                const result = await this.actor.getLogoById(arg0);
                return from_candid_LogoData_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLogoById(arg0);
            return from_candid_LogoData_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLogoByIndex(arg0: bigint): Promise<LogoData> {
        if (this.processError) {
            try {
                const result = await this.actor.getLogoByIndex(arg0);
                return from_candid_LogoData_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLogoByIndex(arg0);
            return from_candid_LogoData_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkflowModeById(arg0: string): Promise<WorkflowMode> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkflowModeById(arg0);
                return from_candid_WorkflowMode_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkflowModeById(arg0);
            return from_candid_WorkflowMode_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
}
function from_candid_AnimationEffect_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnimationEffect): AnimationEffect {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_AnimationProfile2D_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnimationProfile2D): AnimationProfile2D {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_AnimationProfile3D_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnimationProfile3D): AnimationProfile3D {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_LogoData_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LogoData): Promise<LogoData> {
    return await from_candid_record_n19(_uploadFile, _downloadFile, value);
}
async function from_candid_ResponsePayload_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResponsePayload): Promise<ResponsePayload> {
    return await from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_WorkflowMode_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkflowMode): WorkflowMode {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n27(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ResponsePayload]): Promise<ResponsePayload | null> {
    return value.length === 0 ? null : await from_candid_ResponsePayload_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rotation: Array<_LogoData>;
    noEffect: Array<_LogoData>;
    noParticle: Array<_LogoData>;
    effect: Array<_LogoData>;
    particle: Array<_LogoData>;
    scale: Array<_LogoData>;
}): Promise<{
    rotation: Array<LogoData>;
    noEffect: Array<LogoData>;
    noParticle: Array<LogoData>;
    effect: Array<LogoData>;
    particle: Array<LogoData>;
    scale: Array<LogoData>;
}> {
    return {
        rotation: await from_candid_vec_n17(_uploadFile, _downloadFile, value.rotation),
        noEffect: await from_candid_vec_n17(_uploadFile, _downloadFile, value.noEffect),
        noParticle: await from_candid_vec_n17(_uploadFile, _downloadFile, value.noParticle),
        effect: await from_candid_vec_n17(_uploadFile, _downloadFile, value.effect),
        particle: await from_candid_vec_n17(_uploadFile, _downloadFile, value.particle),
        scale: await from_candid_vec_n17(_uploadFile, _downloadFile, value.scale)
    };
}
async function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    animationProfile2D: _AnimationProfile2D;
    animationProfile3D: _AnimationProfile3D;
    inputImage: _ExternalBlob;
    videoFile: [] | [_ExternalBlob];
    modelFile: [] | [_ExternalBlob];
    workflowMode: _WorkflowMode;
}): Promise<{
    id: string;
    animationProfile2D: AnimationProfile2D;
    animationProfile3D: AnimationProfile3D;
    inputImage: ExternalBlob;
    videoFile?: ExternalBlob;
    modelFile?: ExternalBlob;
    workflowMode: WorkflowMode;
}> {
    return {
        id: value.id,
        animationProfile2D: from_candid_AnimationProfile2D_n20(_uploadFile, _downloadFile, value.animationProfile2D),
        animationProfile3D: from_candid_AnimationProfile3D_n25(_uploadFile, _downloadFile, value.animationProfile3D),
        inputImage: await from_candid_ExternalBlob_n27(_uploadFile, _downloadFile, value.inputImage),
        videoFile: record_opt_to_undefined(await from_candid_opt_n28(_uploadFile, _downloadFile, value.videoFile)),
        modelFile: record_opt_to_undefined(await from_candid_opt_n28(_uploadFile, _downloadFile, value.modelFile)),
        workflowMode: from_candid_WorkflowMode_n29(_uploadFile, _downloadFile, value.workflowMode)
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    keyframes: Array<_Keyframe2D>;
    effects: Array<_AnimationEffect>;
    effectConfig2D: _EffectConfig2D;
    rotationConfig: _RotationConfig2D;
}): {
    keyframes: Array<Keyframe2D>;
    effects: Array<AnimationEffect>;
    effectConfig2D: EffectConfig2D;
    rotationConfig: RotationConfig2D;
} {
    return {
        keyframes: value.keyframes,
        effects: from_candid_vec_n22(_uploadFile, _downloadFile, value.effects),
        effectConfig2D: value.effectConfig2D,
        rotationConfig: value.rotationConfig
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    keyframes: Array<_Keyframe3D>;
    effects: Array<_AnimationEffect>;
    effectConfig3D: _EffectConfig3D;
    rotationConfig: _RotationConfig3D;
}): {
    keyframes: Array<Keyframe3D>;
    effects: Array<AnimationEffect>;
    effectConfig3D: EffectConfig3D;
    rotationConfig: RotationConfig3D;
} {
    return {
        keyframes: value.keyframes,
        effects: from_candid_vec_n22(_uploadFile, _downloadFile, value.effects),
        effectConfig3D: value.effectConfig3D,
        rotationConfig: value.rotationConfig
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    particle: null;
} | {
    scale: null;
} | {
    rotate: null;
}): AnimationEffect {
    return "particle" in value ? AnimationEffect.particle : "scale" in value ? AnimationEffect.scale : "rotate" in value ? AnimationEffect.rotate : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    threeDimensional: null;
} | {
    twoDimensional: null;
}): WorkflowMode {
    return "threeDimensional" in value ? WorkflowMode.threeDimensional : "twoDimensional" in value ? WorkflowMode.twoDimensional : value;
}
async function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LogoData>): Promise<Array<LogoData>> {
    return await Promise.all(value.map(async (x)=>await from_candid_LogoData_n18(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AnimationEffect>): Array<AnimationEffect> {
    return value.map((x)=>from_candid_AnimationEffect_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AnimationProfile2D>): Array<AnimationProfile2D> {
    return value.map((x)=>from_candid_AnimationProfile2D_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AnimationProfile3D>): Array<AnimationProfile3D> {
    return value.map((x)=>from_candid_AnimationProfile3D_n25(_uploadFile, _downloadFile, x));
}
function to_candid_AnimationEffect_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnimationEffect): _AnimationEffect {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_WorkflowMode_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkflowMode): _WorkflowMode {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n13(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnimationEffect): {
    particle: null;
} | {
    scale: null;
} | {
    rotate: null;
} {
    return value == AnimationEffect.particle ? {
        particle: null
    } : value == AnimationEffect.scale ? {
        scale: null
    } : value == AnimationEffect.rotate ? {
        rotate: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkflowMode): {
    threeDimensional: null;
} | {
    twoDimensional: null;
} {
    return value == WorkflowMode.threeDimensional ? {
        threeDimensional: null
    } : value == WorkflowMode.twoDimensional ? {
        twoDimensional: null
    } : value;
}
function to_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<AnimationEffect>): Array<_AnimationEffect> {
    return value.map((x)=>to_candid_AnimationEffect_n9(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
